Providing util function to get root Context of a passed Context
Summary:
## Context
Microsoft came back saying that they are facing a `ClassCastException` when sending explicit broadcast events
```
        Intent intent = new Intent(this, MyBroadcastReceiver.class);
        intent.addCategory(Intent.CATEGORY_DEFAULT);
        intent.setAction("com.example.stringpacktest.customintent");
        sendBroadcast(intent);
```
The application crashes with this stacktrace
```
2021-05-19 20:12:44.720 15932-15932/com.example.stringpacktest E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.stringpacktest, PID: 15932
    java.lang.RuntimeException: Unable to instantiate receiver com.example.stringpacktest.MyBroadcastReceiver: java.lang.ClassCastException: com.whatsapp.stringpacks.StringPackContext cannot be cast to android.app.ContextImpl
        at android.app.ActivityThread.handleReceiver(ActivityThread.java:3365)
        at android.app.ActivityThread.access$1200(ActivityThread.java:199)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1661)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.ClassCastException: com.whatsapp.stringpacks.StringPackContext cannot be cast to android.app.ContextImpl
        at android.app.ActivityThread.handleReceiver(ActivityThread.java:3349)
        at android.app.ActivityThread.access$1200(ActivityThread.java:199)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1661)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

After debugging I found that in `ActivityThread#handleReceiver`
```
context = (ContextImpl) app.getBaseContext();
```
Here, `app` is `Application` object and `getBaseContext()` returns `StringPackContext` which cannot be typecasted to `ContextImpl`.

## Fix
Hence, overwriting `getBaseContext()` in `Application` and getting the deepest base Context of the application and returning it.

## More Update
I can ask Microsoft team to overwrite `getBaseContext()` method in their `Application` class but it feels like this is something that should be handled at the library level and not adding to the setup steps.

Hence, I am creating a `ContextUtils` in the library which provides a utils function that returns the root `Context` of the passed Context.
Now, developers need to override `getBaseContext()` in their `Application` class and call `ContextUtils.getRootContext(super.getBaseContext())`.

Updating the README.md as well

Differential Revision: D28560975

fbshipit-source-id: 50ed16e